on: [push, pull_request]

name: fmt,lint,check,build
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Flake checks
        run: nix flake check

      - name: klucznik - check build test clippy
        run: nix build
