on: [push, pull_request]

name: Nix flake tests
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Flake checks
        run: nix flake check

      - name: Flake clippy
        run: nix build .#klucznikClippy

      - name: Flake build klucznik
        run: nix build
